### ISSUE TITLE
Chef resources have been moved to base chef.

### ISSUE THREAD

**Issue by MarkGibbons** [Nordstrom/chefdk_bootstrap#172]
Need to set a base chef version required and remove the dependency on the cookbooks that supply resources that have already been installed.

Deprecated features used!
  Resource apt_preference from a cookbook is overriding the resource from the client. Please upgrade your cookbook or remove the cookbook from your run_list before the next major release of Chef. at 1 location:
    - /Users/xmjg/.chefdk/gem/ruby/2.5.0/gems/chef-14.10.9/lib/chef/log.rb:51:in `caller_location'
   See https://docs.chef.io/deprecations_map_collision.html for further details.
  Resource windows_auto_run from a cookbook is overriding the resource from the client. Please upgrade your cookbook or remove the cookbook from your run_list before the next major release of Chef. at 1 location:
    - /Users/xmjg/.chefdk/gem/ruby/2.5.0/gems/chef-14.10.9/lib/chef/log.rb:51:in `caller_location'
   See https://docs.chef.io/deprecations_map_collision.html for further details.
  Resource windows_feature from a cookbook is overriding the resource from the client. Please upgrade your cookbook or remove the cookbook from your run_list before the next major release of Chef. at 1 location:
    - /Users/xmjg/.chefdk/gem/ruby/2.5.0/gems/chef-14.10.9/lib/chef/log.rb:51:in `caller_location'
   See https://docs.chef.io/deprecations_map_collision.html for further details.
  Resource windows_feature_dism from a cookbook is overriding the resource from the client. Please upgrade your cookbook or remove the cookbook from your run_list before the next major release of Chef. at 1 location:
    - /Users/xmjg/.chefdk/gem/ruby/2.5.0/gems/chef-14.10.9/lib/chef/log.rb:51:in `caller_location'
   See https://docs.chef.io/deprecations_map_collision.html for further details.
  Resource windows_feature_powershell from a cookbook is overriding the resource from the client. Please upgrade your cookbook or remove the cookbook from your run_list before the next major release of Chef. at 1 location:
    - /Users/xmjg/.chefdk/gem/ruby/2.5.0/gems/chef-14.10.9/lib/chef/log.rb:51:in `caller_location'
   See https://docs.chef.io/deprecations_map_collision.html for further details.
  Resource windows_font from a cookbook is overriding the resource from the client. Please upgrade your cookbook or remove the cookbook from your run_list before the next major release of Chef. at 1 location:
    - /Users/xmjg/.chefdk/gem/ruby/2.5.0/gems/chef-14.10.9/lib/chef/log.rb:51:in `caller_location'
   See https://docs.chef.io/deprecations_map_collision.html for further details.
  Resource windows_pagefile from a cookbook is overriding the resource from the client. Please upgrade your cookbook or remove the cookbook from your run_list before the next major release of Chef. at 1 location:
    - /Users/xmjg/.chefdk/gem/ruby/2.5.0/gems/chef-14.10.9/lib/chef/log.rb:51:in `caller_location'
   See https://docs.chef.io/deprecations_map_collision.html for further details.
  Resource windows_path from a cookbook is overriding the resource from the client. Please upgrade your cookbook or remove the cookbook from your run_list before the next major release of Chef. at 1 location:
    - /Users/xmjg/.chefdk/gem/ruby/2.5.0/gems/chef-14.10.9/lib/chef/log.rb:51:in `caller_location'
   See https://docs.chef.io/deprecations_map_collision.html for further details.
  Resource windows_printer from a cookbook is overriding the resource from the client. Please upgrade your cookbook or remove the cookbook from your run_list before the next major release of Chef. at 1 location:
    - /Users/xmjg/.chefdk/gem/ruby/2.5.0/gems/chef-14.10.9/lib/chef/log.rb:51:in `caller_location'
   See https://docs.chef.io/deprecations_map_collision.html for further details.
  Resource windows_printer_port from a cookbook is overriding the resource from the client. Please upgrade your cookbook or remove the cookbook from your run_list before the next major release of Chef. at 1 location:
    - /Users/xmjg/.chefdk/gem/ruby/2.5.0/gems/chef-14.10.9/lib/chef/log.rb:51:in `caller_location'
   See https://docs.chef.io/deprecations_map_collision.html for further details.
  Resource windows_shortcut from a cookbook is overriding the resource from the client. Please upgrade your cookbook or remove the cookbook from your run_list before the next major release of Chef. at 1 location:
    - /Users/xmjg/.chefdk/gem/ruby/2.5.0/gems/chef-14.10.9/lib/chef/log.rb:51:in `caller_location'
   See https://docs.chef.io/deprecations_map_collision.html for further details.
  Resource windows_task from a cookbook is overriding the resource from the client. Please upgrade your cookbook or remove the cookbook from your run_list before the next major release of Chef. at 1 location:
    - /Users/xmjg/.chefdk/gem/ruby/2.5.0/gems/chef-14.10.9/lib/chef/log.rb:51:in `caller_location'
   See https://docs.chef.io/deprecations_map_collision.html for further details.

Resource homebrew_cask from a cookbook is overriding the resource from the client. 

Please upgrade your cookbook or remove the cookbook from your run_list before the next major release of Chef. at 1 location:
    - /Users/xmjg/.chefdk/gem/ruby/2.5.0/gems/chef-14.10.9/lib/chef/log.rb:51:in `caller_location'
   See https://docs.chef.io/deprecations_map_collision.html for further details.
  Resource homebrew_tap from a cookbook is overriding the resource from the client. Please upgrade your cookbook or remove the cookbook from your run_list before the next major release of Chef. at 1 location:
    - /Users/xmjg/.chefdk/gem/ruby/2.5.0/gems/chef-14.10.9/lib/chef/log.rb:51:in `caller_location'
   See https://docs.chef.io/deprecations_map_collision.html for further details.
  Resource dmg_package from a cookbook is overriding the resource from the client. Please upgrade your cookbook or remove the cookbook from your run_list before the next major release of Chef. at 1 location:
    - /Users/xmjg/.chefdk/gem/ruby/2.5.0/gems/chef-14.10.9/lib/chef/log.rb:51:in `caller_location'
   See https://docs.chef.io/deprecations_map_collision.html for further details.

**Comment by MarkGibbons** [comment]
Fixed by #175
