### ISSUE TITLE
Buff::Errors::InvalidConfig error when running ChefDK_bootstrap script (Berkshelf)

### ISSUE THREAD

**Issue by dougireton** [Nordstrom/chefdk_bootstrap#42]
## Error
When running the boostrap script you may encounter an error like the following:

```
Installing ChefDK...
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/buff-config-1.0.1/lib/buff/config/ruby.rb:30:in `rescue in initializ
e': uninitialized constant Buff::Config::Ruby::Evaluator::Chef (Buff::Errors::InvalidConfig)
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/buff-config-1.0.1/lib/buff/config/ruby.rb:25:in `initia
lize'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/buff-config-1.0.1/lib/buff/config/ruby.rb:17:in `new'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/buff-config-1.0.1/lib/buff/config/ruby.rb:17:in `parse'

        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/buff-config-1.0.1/lib/buff/config/ruby.rb:119:in `from_
ruby'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/buff-config-1.0.1/lib/buff/config/ruby.rb:112:in `initi
alize'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.2.0/lib/ridley/chef/config.rb:83:in `initializ
e'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-3.3.0/lib/berkshelf.rb:90:in `new'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-3.3.0/lib/berkshelf.rb:90:in `chef_config'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-3.3.0/lib/berkshelf/config.rb:80:in `<class:C
onfig>'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-3.3.0/lib/berkshelf/config.rb:4:in `<module:B
erkshelf>'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-3.3.0/lib/berkshelf/config.rb:3:in `<top (req
uired)>'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-3.3.0/lib/berkshelf/cookbook_generator.rb:3:i
n `require_relative'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-3.3.0/lib/berkshelf/cookbook_generator.rb:3:i
n `<class:CookbookGenerator>'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-3.3.0/lib/berkshelf/cookbook_generator.rb:2:i
n `<module:Berkshelf>'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-3.3.0/lib/berkshelf/cookbook_generator.rb:1:i
n `<top (required)>'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-3.3.0/lib/berkshelf.rb:197:in `require_relati
ve'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-3.3.0/lib/berkshelf.rb:197:in `<top (required
)>'
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-3.3.0/lib/berkshelf/cli.rb:1:in `<top (requir
ed)>'
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-3.3.0/bin/berks:3:in `<top (required)>'
        from C:/opscode/chefdk/bin/berks:43:in `load'
        from C:/opscode/chefdk/bin/berks:43:in `<main>'
Starting Chef Client, version 12.4.4
resolving cookbooks for run list: ["chefdk_bootstrap"]

================================================================================
Error Resolving Cookbooks for Run List:
================================================================================

Missing Cookbooks:
------------------
No such cookbook: chefdk_bootstrap

Expanded Run List:
------------------
* chefdk_bootstrap


Running handlers:
[2015-10-07T17:57:02-07:00] ERROR: Running exception handlers
Running handlers complete
[2015-10-07T17:57:02-07:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 31.391 seconds
[2015-10-07T17:57:02-07:00] FATAL: Stacktrace dumped to C:/Users/uipu/chef/local-mode-cache/cache/chef-stacktrace.out
[2015-10-07T17:57:02-07:00] FATAL: Net::HTTPServerException: 412 "Precondition Failed"
```

## Cause
This is this [issue in Berkshelf](https://github.com/berkshelf/berkshelf/issues/965).

The issue is caused by having a line like this in your `knife.rb`:
`Chef::Config.from_file(knife_override) if File.exist?(knife_override)`

## Solution

Replace the offending line in your knife.rb with this code:

```ruby
# See this Berkshelf issue for why we can't call Chef::Config.from_file()
# https://github.com/berkshelf/berkshelf/issues/965
# This code is what Chef::Config.from_file() does.
if File.exists?(org_override) && File.readable?(org_override)
  self.instance_eval(IO.read(org_override), org_override, 1)
end
```

**Comment by dougireton** [comment]
This is not actually a bug in chefdk_bootstrap. Closing.
